### ISSUE TITLE
Missing config files?

### ISSUE THREAD

**Issue by YalithKBK** [EwyBoy/CHA-S#1]
Downloaded and ran 1.3 in 1.12.2. Recipes appear just fine. I shut down Minecraft and wanted to change the recipes to the old ones, however, I do not see the config file in my .minecraft/config folder.

**Comment by EwyBoy** [comment]
Hmm, I might have removed the old recipes option or the forge version I built the mod on was outdated. Going to look into it now and release a fix.

**Comment by Robzekrom** [comment]
Was this ever fixed?
