### ISSUE TITLE
v1.3 for 1.16 Forge [2.04 KB - Sep 11, 2020] failed but 'other' v1.3 for 1.16 [4.59 KB - Jun 30, 2020] Forge works after adding 'license="..."' in 'mods.toml'

### ISSUE THREAD

**Issue by markygnlg** [EwyBoy/CHA-S#4]
Hi,
As stated in the title, v1.3 for 1.16 Forge [2.04 KB - Sep 11, 2020 - filename 'CHAS v1.3 for 1.16 Forge.jar'] failed but the 'other' v1.3 for 1.16 Forge [4.59 KB - Jun 30, 2020 - filename 'craftablehorsearmour-1.3.jar'] works after adding 'license="..."' in 'mods.toml' (ie. it comes up with the error 'missing license info').

Thanks for the great mod btw,
M.
EDIT: I'm using minecraft -1.16.3 & forge-34.1.5
EDIT2: I tested only with JEI; ie. I did not use the crafting bench to test the recipes.

**Comment by EwyBoy** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/cha-s/files/3116758
