### ISSUE TITLE
v1.16.4 forge recipes don't work

### ISSUE THREAD

**Issue by Nekohime89** [EwyBoy/CHA-S#5]
[latest.log](https://github.com/EwyBoy/CHA-S/files/5543059/latest.log)
![temp](https://user-images.githubusercontent.com/68340265/99195882-ccf88d80-2745-11eb-9fa7-6b30d2e6a766.png)

None of the horse armors or saddle recipes work.

**Comment by EwyBoy** [comment]
Something broke in the build that was uploaded to CurseForge. I am working on fix that will resolve this issue. 
Thanks for reporting.

-Ewy

**Comment by EwyBoy** [comment]
Fixed: https://www.curseforge.com/minecraft/mc-mods/cha-s/files/3116758
